-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 09:21:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cars_Store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cars_Store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cars_Store` DEFAULT CHARACTER SET utf8 ;
USE `Cars_Store` ;

-- -----------------------------------------------------
-- Table `Cars_Store`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Marca` (
  `Cod_Marca` INT NOT NULL,
  PRIMARY KEY (`Cod_Marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Modelo` (
  `Cod_modelo` INT NOT NULL,
  PRIMARY KEY (`Cod_modelo`))
ENGINE = InnoDB;
INSERT INTO `Cars_Store`.`categoria_Modelo`(`Cod`,`Nome`) values(null,Integra);
INSERT INTO `Cars_Store`.`categoria_Modelo`(`Cod`,`Nome`) values(null,Legend);
INSERT INTO `Cars_Store`.`categoria_Modelo`(`Cod`,`Nome`) values(null,NSX);

-- -----------------------------------------------------
-- Table `Cars_Store`.`Automóvel`
-- ----------------------------------------------------- 
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Automóvel` (
  `idAutomóvel` INT NOT NULL,
  `Ano_Modelo` INT NOT NULL,
  `Ano_Fabricação` INT NOT NULL,
  `Versão` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Foto_Carro` VARCHAR(45) NOT NULL,
  `Valor` INT NOT NULL,
  `Marca_Cod_Marca` INT NOT NULL,
  `Modelo_Cod_modelo` INT NOT NULL,
  PRIMARY KEY (`idAutomóvel`, `Marca_Cod_Marca`, `Modelo_Cod_modelo`),
  INDEX `fk_Automóvel_Marca1_idx` (`Marca_Cod_Marca` ASC) VISIBLE,
  INDEX `fk_Automóvel_Modelo1_idx` (`Modelo_Cod_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_Automóvel_Marca1`
    FOREIGN KEY (`Marca_Cod_Marca`)
    REFERENCES `Cars_Store`.`Marca` (`Cod_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Automóvel_Modelo1`
    FOREIGN KEY (`Modelo_Cod_modelo`)
    REFERENCES `Cars_Store`.`Modelo` (`Cod_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Empresa` (
  `idEmpresa` INT NULL,
  `CPNJ` INT NOT NULL,
  `Nome_Empresa` VARCHAR(45) NOT NULL,
  `Nome_Representante` VARCHAR(45) NOT NULL,
  `CPF_Representante` INT NOT NULL,
  `Telefone_Representante` INT NOT NULL,
  `Email_Representante` VARCHAR(45) NOT NULL,
  `Automóvel_idAutomóvel` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `Automóvel_idAutomóvel`),
  INDEX `fk_Empresa_Automóvel_idx` (`Automóvel_idAutomóvel` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Automóvel`
    FOREIGN KEY (`Automóvel_idAutomóvel`)
    REFERENCES `Cars_Store`.`Automóvel` (`idAutomóvel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Compra` (
  `idCompra` INT NOT NULL,
  `Compracol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Empresa_Automóvel_idAutomóvel` INT NOT NULL,
  `Compra_idCompra` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Empresa_idEmpresa`, `Empresa_Automóvel_idAutomóvel`, `Compra_idCompra`),
  INDEX `fk_Usuario_Empresa1_idx` (`Empresa_idEmpresa` ASC, `Empresa_Automóvel_idAutomóvel` ASC) VISIBLE,
  INDEX `fk_Usuario_Compra1_idx` (`Compra_idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa` , `Empresa_Automóvel_idAutomóvel`)
    REFERENCES `Cars_Store`.`Empresa` (`idEmpresa` , `Automóvel_idAutomóvel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `Cars_Store`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Cor` (
  `Cod_Cor` INT NOT NULL,
  `Cor_Cod_Cor` INT NOT NULL,
  PRIMARY KEY (`Cod_Cor`),
  INDEX `fk_Cor_Cor1_idx` (`Cor_Cod_Cor` ASC) VISIBLE,
  CONSTRAINT `fk_Cor_Cor1`
    FOREIGN KEY (`Cor_Cod_Cor`)
    REFERENCES `Cars_Store`.`Cor` (`Cod_Cor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Modelo_has_Cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Modelo_has_Cor` (
  `Modelo_Cod_modelo` INT NOT NULL,
  `Cor_Cod_Cor` INT NOT NULL,
  PRIMARY KEY (`Modelo_Cod_modelo`, `Cor_Cod_Cor`),
  INDEX `fk_Modelo_has_Cor_Cor1_idx` (`Cor_Cod_Cor` ASC) VISIBLE,
  INDEX `fk_Modelo_has_Cor_Modelo1_idx` (`Modelo_Cod_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_Modelo_has_Cor_Modelo1`
    FOREIGN KEY (`Modelo_Cod_modelo`)
    REFERENCES `Cars_Store`.`Modelo` (`Cod_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modelo_has_Cor_Cor1`
    FOREIGN KEY (`Cor_Cod_Cor`)
    REFERENCES `Cars_Store`.`Cor` (`Cod_Cor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cars_Store`.`Automóvel_has_Cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cars_Store`.`Automóvel_has_Cor` (
  `Automóvel_idAutomóvel` INT NOT NULL,
  `Automóvel_Marca_Cod_Marca` INT NOT NULL,
  `Automóvel_Modelo_Cod_modelo` INT NOT NULL,
  `Cor_Cod_Cor` INT NOT NULL,
  PRIMARY KEY (`Automóvel_idAutomóvel`, `Automóvel_Marca_Cod_Marca`, `Automóvel_Modelo_Cod_modelo`, `Cor_Cod_Cor`),
  INDEX `fk_Automóvel_has_Cor_Cor1_idx` (`Cor_Cod_Cor` ASC) VISIBLE,
  INDEX `fk_Automóvel_has_Cor_Automóvel1_idx` (`Automóvel_idAutomóvel` ASC, `Automóvel_Marca_Cod_Marca` ASC, `Automóvel_Modelo_Cod_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_Automóvel_has_Cor_Automóvel1`
    FOREIGN KEY (`Automóvel_idAutomóvel` , `Automóvel_Marca_Cod_Marca` , `Automóvel_Modelo_Cod_modelo`)
    REFERENCES `Cars_Store`.`Automóvel` (`idAutomóvel` , `Marca_Cod_Marca` , `Modelo_Cod_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Automóvel_has_Cor_Cor1`
    FOREIGN KEY (`Cor_Cod_Cor`)
    REFERENCES `Cars_Store`.`Cor` (`Cod_Cor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
